jobs:
  build:
    name: Build
    secrets: inherit
    strategy:
      matrix:
        jdk:
        - 17
        os:
        - ubuntu-latest
        - windows-latest
    uses: spring-io/spring-security-release-tools/.github/workflows/build.yml@v1
    with:
      distribution: temurin
      java-version: ${{ matrix.jdk }}
      runs-on: ${{ matrix.os }}
  deploy-artifacts:
    name: Deploy Artifacts
    needs:
    - build
    - test
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-artifacts.yml@v1
    with:
      should-deploy-artifacts: ${{ needs.build.outputs.should-deploy-artifacts }}
  deploy-docs:
    name: Deploy Docs
    needs:
    - build
    - test
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-docs.yml@v1
    with:
      should-deploy-docs: ${{ needs.build.outputs.should-deploy-artifacts }}
  perform-release:
    name: Perform Release
    needs:
    - deploy-artifacts
    - deploy-docs
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/perform-release.yml@v1
    with:
      artifact-path: org/springframework/security/spring-security-oauth2-authorization-server
      milestone-repo-url: https://repo.spring.io/artifactory/milestone
      project-version: ${{ needs.deploy-artifacts.outputs.project-version }}
      release-repo-url: https://repo1.maven.org/maven2
      should-perform-release: ${{ needs.deploy-artifacts.outputs.artifacts-deployed
        }}
      slack-announcing-id: spring-authorization-server-announcing
  test:
    name: Test Against Snapshots
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/test.yml@v1
    with:
      test-args: --refresh-dependencies --stacktrace -PforceMavenRepositories=snapshot
        -PspringFrameworkVersion=6.1.+ -PspringSecurityVersion=6.3.+
name: Build and Deploy
on:
  repository_dispatch:
    types: trigger-ga___continuous-integration-workflow.yml
