jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: spring-io/spring-gradle-build-action@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 17
        os:
        - ubuntu-latest
        - windows-latest
name: PR build
on:
  repository_dispatch:
    types: trigger-ga___pr-build-workflow.yml
